name: Bug report
description: Gebruik dit template om issue te melden die onverwacht niet goed werken
labels: "\U0001F41E bug"
body:
  - type: input
    id: omschrijving
    attributes:
      label: 📚 Omschrijving bug
      description: Een korte omschrijving van de bug
  - type: input
    id: verwacht-gedrag
    attributes:
      label: 👌 Verwacht gedrag
      description: Een korte duidelijke beschrijving van wat je had verwacht dat zou gebeuren
  - type: textarea
    id: stappen
    attributes:
     label: 🔍 Stappen om te reproduceren
     description: De stappen die nodig zijn om de bug na te doen
     value: |
       1. Go to '...'
       2. Click on '....'
       3. Scroll down to '....'
       4. See error
  - type: input
    id: context
    attributes:
      label: 🔦 Context
      description: Randvoorwaarden (ingelogde gebruiker, browser, etc.)
      placeholder: |
        Treedt op sinds:
  - type: textarea
    id: contact
    attributes:
      label: 🙋‍ Contactinformatie melder
      description: |
        De contactinformatie van het bedrijf / de persoon die dit issue gemeld heeft
        - De naam van de persoon die dit issue heeft gemeld
        - De naam van het bedrijf wat dit issue heeft gemeld
        - Extra informatie zoals een link naar externe conversaties of een pdf van een email
      value: |
        Persoon: 
        Bedrijf: 
        Extra informatie: 
