name: Feature request
description: Gebruik dit template om een nieuwe feature aan te vragen
labels: "\U0001F680 feature"
body:
  - type: input
    id: omschrijving
    attributes:
      label: 📚 Functionele omschrijving
      description: Een functionele omschrijving van de feature. Beschrijf in detail hoe je wilt dat het gaat werken
  - type: textarea
    id: contact
    attributes:
      label: 🙋‍ Contactinformatie melder
      description: |
        De contactinformatie van het bedrijf / de persoon die dit issue gemeld heeft
        - De naam van de persoon die dit issue heeft gemeld
        - De naam van het bedrijf wat dit issue heeft gemeld
        - Extra informatie zoals een link naar externe conversaties of een pdf van een email
      value: |
        Persoon: 
        Bedrijf: 
        Extra informatie: 
  - type: textarea
    id: externe-afhankelijkheden
    attributes:
      label: 👀 Externe afhankelijkheden
      description: Externe afhankelijkheden waar we op moeten wachten voordat we de feature kunnen maken. Zoals bv, authenticatie ontvangen voor communicatie met extern systeem 
